modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
logoFile="logo.png"
description='''${mod_description}'''
[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="geckolib"
mandatory=true
versionRange="[4.4.9, )"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="tardis"
mandatory=true
versionRange="[1.1.2, )"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="sgjourney"
mandatory=true
versionRange="[0.6.39, )"
ordering="NONE"
side="BOTH"